[llamadas_internas]

# Colgar la llamada si no hay actividad de audio durante 20 segundos
exten => _[1-5]XXX, 1, Dial(PJSIP/${EXTEN}, 20)

#Asterisk elimina el 9 del número marcado para poder enrutar la llamada 
[salientes_redpublica]
exten => _9X., 1, Dial(PJSIP/${EXTEN:1}@trunk_redpublica, 20)

#Asterisk elimina el 8 del número marcado para poder enrutar
# la llamada a la troncal SIP correspondiente.
[salientes_troncal_sip]
exten => _8X., 1, Dial(PJSIP/${EXTEN:1}@trunk_sip, 20)
