# Escogemos este protocolo debido a que es el más común y compatible con la mayoría de los dispositivos SIP.
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=127.0.0.1
external_signaling_address=127.0.0.1

# Nuestras extensiones SIP. Cada extensión tiene un endpoint, un AOR y un auth.
[1001]
type=endpoint
context=llamadas_internas
allow=ulaw
aors=1001
auth=1001-auth
rtp_timeout_hold=900
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

#Con la libreria de PJSIP podemos definir multiples secciones con el mismo nombre si el tipo difiere
[1001]
type=aor
max_contacts=1

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=1001

[1002]
type=endpoint
context=llamadas_internas
allow=ulaw
aors=1002
auth=1002-auth
rtp_timeout_hold=900
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1002]
type=aor
max_contacts=1

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=1002
